name: Check
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        run: make install
      - name: Lint
        run: make lint
  test:
    needs: [lint]
    strategy:
      matrix:
        node-version: [20.x]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      - name: Install
        run: make install
      - name: Test
        run: make test
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v4.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_SevHope }}
        with:
          coverageCommand: make test-coverage
          debug: true